image: alpine:3.15
image: node:16.13.2

stages:
  - Release

Build:
  stage: Release
  only:
    - develop
  cache: {}
  script:
    - npm ci
    - npx ng build -c Exzy
  artifacts:
    paths:
      - dist

Build-Release:
  stage: Release
  only:
    - tags
  cache: {}
  script:
    - IFS=- read -r TAGVERSION PROJECTNAME <<< "$CI_COMMIT_TAG"
    - echo $CI_COMMIT_TAG
    - npm ci
    - npx ng build -c $PROJECTNAME
  artifacts:
    paths:
      - dist
